- hosts: all
  become: true
  tasks:
    - name: Pull calculator docker image
      community.docker.docker_image:
        name: pantprakhar/spe-mini-project
        source: pull

    - name: Launch the calculator container
      docker_container:
        name: scientific_calculator
        image: pantprakhar/spe-mini-project
        state: started
        ports:
        -  8000:3000
